const urls = {
  LOGIN: "login",
  AUTH: "auth",
  USERS: "users",
  GET_ALL_USER: "get-all-users",
  TRANSACTIONS: "transactions",
  USER: "user",
  TECHNOLOGIES: "technologies",
  JOBTITLE: "jobTitle",
  POSTS: "posts",
  GET_ALL_POST: "get-all-post",
  UPLOADS: "uploads",
  UPLOAD: "upload",
  CREATE_NEW_POST: "create-new-post",
  DELETE_POST: "delete-post",
  UPDATE_POST: "update-post",
  TAGS: "tags",
  V2: "v2",
  REGISTER: "register",
  CHAT_GROUP: "chat-groups",
  MESSAGES: "messages",
  GROUP: "group",
};
export default urls;
